version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: first_uae_ai
      POSTGRES_USER: orionix
      POSTGRES_PASSWORD: orionpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
volumes:
  postgres_data:
