version: '3.8'

services:
  api:
    build: .
    container_name: first-uae-ai-api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-first_uae_ai}
      POSTGRES_USER: ${POSTGRES_USER:-orionix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orionpass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-orionix} -d ${POSTGRES_DB:-first_uae_ai}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
